"""Seed 60 diverse meals into admin_meals collection."""
import os
import asyncio
import random
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
DB_NAME = os.environ.get("DB_NAME", "test_database")

def now_utc():
    return datetime.now(timezone.utc).isoformat()

FOOD_IMAGES = [
    "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80",
    "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",
    "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80",
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80",
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
    "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=600&q=80",
    "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&q=80",
    "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80",
    "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80",
    "https://images.unsplash.com/photo-1432139509613-5c4255a1d197?w=600&q=80",
    "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80",
    "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=600&q=80",
    "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=80",
    "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=600&q=80",
    "https://images.unsplash.com/photo-1543340904-0eb7ebe3b5c1?w=600&q=80",
    "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=600&q=80",
    "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80",
    "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80",
]

MEALS = [
    # ── BREAKFAST ──────────────────────────────────────────────
    {
        "title": "Avocado Toast with Poached Egg",
        "about": "Creamy avocado on whole-grain toast topped with perfectly poached eggs and everything bagel seasoning.",
        "category": "High Protein",
        "menuType": "Breakfast",
        "calories": 380, "proteins": 18, "fat": 22, "carbs": 32,
        "servings": 1,
        "ingredients": [
            {"name": "Whole grain bread", "quantity": "2", "unit": "piece"},
            {"name": "Avocado", "quantity": "1", "unit": "piece"},
            {"name": "Eggs", "quantity": "2", "unit": "piece"},
            {"name": "Lemon juice", "quantity": "1", "unit": "tsp"},
            {"name": "Everything bagel seasoning", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Toast the bread until golden.", "Mash avocado with lemon juice and salt.", "Poach eggs for 3–4 minutes.", "Spread avocado on toast, top with poached eggs and seasoning."],
        "notes": "Add red pepper flakes for heat.",
    },
    {
        "title": "Greek Yogurt Parfait",
        "about": "Layered Greek yogurt with granola, mixed berries, and a drizzle of honey. Quick and protein-packed.",
        "category": "Balanced",
        "menuType": "Breakfast",
        "calories": 320, "proteins": 22, "fat": 8, "carbs": 42,
        "servings": 1,
        "ingredients": [
            {"name": "Greek yogurt (plain, 2%)", "quantity": "200", "unit": "g"},
            {"name": "Granola", "quantity": "40", "unit": "g"},
            {"name": "Mixed berries", "quantity": "80", "unit": "g"},
            {"name": "Honey", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Layer yogurt in a glass.", "Add granola, then berries.", "Drizzle with honey and serve immediately."],
        "notes": "Use low-sugar granola for cleaner macros.",
    },
    {
        "title": "Overnight Oats with Berries",
        "about": "Rolled oats soaked overnight in almond milk with chia seeds and fresh berries. Meal-prep friendly.",
        "category": "Clean Eating",
        "menuType": "Breakfast",
        "calories": 350, "proteins": 14, "fat": 10, "carbs": 55,
        "servings": 1,
        "ingredients": [
            {"name": "Rolled oats", "quantity": "80", "unit": "g"},
            {"name": "Almond milk", "quantity": "200", "unit": "ml"},
            {"name": "Chia seeds", "quantity": "1", "unit": "tbsp"},
            {"name": "Mixed berries", "quantity": "100", "unit": "g"},
            {"name": "Maple syrup", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Mix oats, almond milk, and chia seeds in a jar.", "Refrigerate overnight.", "Top with berries and maple syrup before serving."],
        "notes": "Add protein powder for an extra 20g protein.",
    },
    {
        "title": "Protein Pancakes",
        "about": "Fluffy high-protein pancakes made with banana, oats, and whey protein. No refined sugar.",
        "category": "High Protein",
        "menuType": "Breakfast",
        "calories": 420, "proteins": 30, "fat": 12, "carbs": 48,
        "servings": 2,
        "ingredients": [
            {"name": "Banana (ripe)", "quantity": "1", "unit": "piece"},
            {"name": "Rolled oats", "quantity": "60", "unit": "g"},
            {"name": "Whey protein powder", "quantity": "30", "unit": "g"},
            {"name": "Eggs", "quantity": "2", "unit": "piece"},
            {"name": "Baking powder", "quantity": "0.5", "unit": "tsp"},
        ],
        "directions": ["Blend all ingredients until smooth.", "Heat a non-stick pan over medium heat.", "Pour ¼ cup batter per pancake, cook 2 min each side.", "Serve with fresh berries."],
        "notes": "Works well with vanilla or chocolate protein.",
    },
    {
        "title": "Veggie Egg White Omelette",
        "about": "Light egg white omelette packed with spinach, mushrooms, and feta cheese for a low-calorie start.",
        "category": "Healthy",
        "menuType": "Breakfast",
        "calories": 220, "proteins": 26, "fat": 8, "carbs": 8,
        "servings": 1,
        "ingredients": [
            {"name": "Egg whites", "quantity": "6", "unit": "piece"},
            {"name": "Baby spinach", "quantity": "50", "unit": "g"},
            {"name": "Mushrooms", "quantity": "60", "unit": "g"},
            {"name": "Feta cheese", "quantity": "30", "unit": "g"},
            {"name": "Bell pepper", "quantity": "0.5", "unit": "piece"},
        ],
        "directions": ["Sauté mushrooms and bell pepper until soft.", "Add spinach and cook until wilted.", "Pour in egg whites, cook until set.", "Fold in half with feta and serve."],
        "notes": "Season well — egg whites are bland on their own.",
    },
    {
        "title": "Acai Power Bowl",
        "about": "Antioxidant-rich acai bowl with banana, granola, coconut flakes, and fresh tropical fruits.",
        "category": "Vegan",
        "menuType": "Breakfast",
        "calories": 340, "proteins": 8, "fat": 10, "carbs": 60,
        "servings": 1,
        "ingredients": [
            {"name": "Frozen acai packets", "quantity": "100", "unit": "g"},
            {"name": "Banana (frozen)", "quantity": "1", "unit": "piece"},
            {"name": "Almond milk", "quantity": "60", "unit": "ml"},
            {"name": "Granola", "quantity": "30", "unit": "g"},
            {"name": "Coconut flakes", "quantity": "10", "unit": "g"},
            {"name": "Mango slices", "quantity": "50", "unit": "g"},
        ],
        "directions": ["Blend acai, frozen banana, and almond milk until thick.", "Pour into a bowl.", "Top with granola, coconut flakes, and mango."],
        "notes": "Keep it thick — it shouldn't be drinkable.",
    },
    {
        "title": "Sweet Potato & Spinach Breakfast Hash",
        "about": "Hearty sweet potato hash with eggs, spinach, and turkey sausage. Satisfying and nutrient-dense.",
        "category": "Balanced",
        "menuType": "Breakfast",
        "calories": 410, "proteins": 28, "fat": 16, "carbs": 38,
        "servings": 2,
        "ingredients": [
            {"name": "Sweet potato (diced)", "quantity": "200", "unit": "g"},
            {"name": "Turkey sausage", "quantity": "120", "unit": "g"},
            {"name": "Baby spinach", "quantity": "60", "unit": "g"},
            {"name": "Eggs", "quantity": "3", "unit": "piece"},
            {"name": "Olive oil", "quantity": "1", "unit": "tbsp"},
            {"name": "Paprika", "quantity": "0.5", "unit": "tsp"},
        ],
        "directions": ["Cook sweet potato in olive oil 10 min until golden.", "Add turkey sausage and cook through.", "Add spinach until wilted.", "Create wells, crack in eggs, cover and cook 4 min."],
        "notes": "Great for meal prep — keeps 4 days refrigerated.",
    },
    {
        "title": "Chia Seed Pudding",
        "about": "Simple 2-ingredient chia pudding base with coconut milk, topped with mango and lime zest.",
        "category": "Vegan",
        "menuType": "Breakfast",
        "calories": 280, "proteins": 8, "fat": 14, "carbs": 32,
        "servings": 1,
        "ingredients": [
            {"name": "Chia seeds", "quantity": "40", "unit": "g"},
            {"name": "Coconut milk", "quantity": "240", "unit": "ml"},
            {"name": "Maple syrup", "quantity": "1", "unit": "tbsp"},
            {"name": "Vanilla extract", "quantity": "0.5", "unit": "tsp"},
            {"name": "Mango (diced)", "quantity": "80", "unit": "g"},
        ],
        "directions": ["Mix chia, coconut milk, maple syrup, and vanilla.", "Refrigerate at least 4 hours or overnight.", "Stir and top with mango before serving."],
        "notes": "Stir after 30 minutes to prevent clumping.",
    },

    # ── LUNCH ──────────────────────────────────────────────────
    {
        "title": "Grilled Chicken Caesar Salad",
        "about": "Classic Caesar with grilled chicken breast, romaine, parmesan, and whole-grain croutons.",
        "category": "High Protein",
        "menuType": "Lunch",
        "calories": 450, "proteins": 42, "fat": 22, "carbs": 18,
        "servings": 1,
        "ingredients": [
            {"name": "Chicken breast", "quantity": "180", "unit": "g"},
            {"name": "Romaine lettuce", "quantity": "150", "unit": "g"},
            {"name": "Parmesan cheese", "quantity": "20", "unit": "g"},
            {"name": "Whole-grain croutons", "quantity": "30", "unit": "g"},
            {"name": "Caesar dressing (light)", "quantity": "2", "unit": "tbsp"},
        ],
        "directions": ["Season and grill chicken 6 min per side.", "Chop romaine and toss with dressing.", "Slice chicken, top salad.", "Finish with parmesan and croutons."],
        "notes": "Use light Caesar dressing to cut 80 calories.",
    },
    {
        "title": "Mediterranean Chickpea Bowl",
        "about": "Roasted chickpeas, cucumber, tomato, olives, and tzatziki over brown rice. Vegan and filling.",
        "category": "Mediterranean",
        "menuType": "Lunch",
        "calories": 480, "proteins": 18, "fat": 16, "carbs": 62,
        "servings": 1,
        "ingredients": [
            {"name": "Chickpeas (cooked)", "quantity": "150", "unit": "g"},
            {"name": "Brown rice (cooked)", "quantity": "120", "unit": "g"},
            {"name": "Cucumber (diced)", "quantity": "80", "unit": "g"},
            {"name": "Cherry tomatoes", "quantity": "80", "unit": "g"},
            {"name": "Kalamata olives", "quantity": "20", "unit": "g"},
            {"name": "Tzatziki", "quantity": "60", "unit": "g"},
            {"name": "Olive oil", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Roast chickpeas with olive oil and spices 25 min at 200°C.", "Layer rice, chickpeas, and vegetables.", "Top with tzatziki and olives."],
        "notes": "Add sumac or za'atar for authentic flavor.",
    },
    {
        "title": "Turkey & Avocado Wrap",
        "about": "Lean turkey, creamy avocado, and crunchy veggies in a spinach tortilla. High protein and portable.",
        "category": "Clean Eating",
        "menuType": "Lunch",
        "calories": 420, "proteins": 32, "fat": 18, "carbs": 35,
        "servings": 1,
        "ingredients": [
            {"name": "Spinach tortilla", "quantity": "1", "unit": "piece"},
            {"name": "Turkey breast (sliced)", "quantity": "120", "unit": "g"},
            {"name": "Avocado", "quantity": "0.5", "unit": "piece"},
            {"name": "Romaine lettuce", "quantity": "40", "unit": "g"},
            {"name": "Tomato (sliced)", "quantity": "60", "unit": "g"},
            {"name": "Dijon mustard", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Spread avocado and mustard on tortilla.", "Layer turkey, lettuce, and tomato.", "Roll tightly and slice in half."],
        "notes": "Wrap in foil for easy on-the-go lunch.",
    },
    {
        "title": "Quinoa Black Bean Burrito Bowl",
        "about": "Protein-packed vegan bowl with seasoned black beans, quinoa, salsa, guac, and lime crema.",
        "category": "Vegan",
        "menuType": "Lunch",
        "calories": 510, "proteins": 22, "fat": 14, "carbs": 70,
        "servings": 1,
        "ingredients": [
            {"name": "Quinoa (cooked)", "quantity": "150", "unit": "g"},
            {"name": "Black beans (cooked)", "quantity": "120", "unit": "g"},
            {"name": "Corn kernels", "quantity": "60", "unit": "g"},
            {"name": "Salsa", "quantity": "60", "unit": "g"},
            {"name": "Avocado (sliced)", "quantity": "0.5", "unit": "piece"},
            {"name": "Lime juice", "quantity": "1", "unit": "tbsp"},
            {"name": "Cilantro", "quantity": "10", "unit": "g"},
        ],
        "directions": ["Warm quinoa and black beans.", "Layer in a bowl with corn and salsa.", "Top with avocado, lime juice, and cilantro."],
        "notes": "Add jalapeño for a spicy kick.",
    },
    {
        "title": "Asian Sesame Chicken Salad",
        "about": "Grilled chicken over shredded cabbage and edamame with sesame ginger dressing. Restaurant-quality at home.",
        "category": "High Protein",
        "menuType": "Lunch",
        "calories": 400, "proteins": 35, "fat": 18, "carbs": 22,
        "servings": 1,
        "ingredients": [
            {"name": "Chicken breast", "quantity": "160", "unit": "g"},
            {"name": "Shredded cabbage", "quantity": "150", "unit": "g"},
            {"name": "Edamame", "quantity": "60", "unit": "g"},
            {"name": "Carrots (shredded)", "quantity": "50", "unit": "g"},
            {"name": "Sesame seeds", "quantity": "1", "unit": "tbsp"},
            {"name": "Sesame ginger dressing", "quantity": "2", "unit": "tbsp"},
        ],
        "directions": ["Grill chicken, slice thin.", "Toss cabbage, edamame, carrots in dressing.", "Top with chicken and sesame seeds."],
        "notes": "Mandarin orange slices add great flavor.",
    },
    {
        "title": "Tuna & White Bean Salad",
        "about": "Protein-dense Mediterranean-style salad with canned tuna, white beans, capers, and herbs.",
        "category": "Mediterranean",
        "menuType": "Lunch",
        "calories": 360, "proteins": 38, "fat": 10, "carbs": 28,
        "servings": 1,
        "ingredients": [
            {"name": "Canned tuna (in water)", "quantity": "150", "unit": "g"},
            {"name": "White beans (cooked)", "quantity": "100", "unit": "g"},
            {"name": "Capers", "quantity": "1", "unit": "tbsp"},
            {"name": "Red onion", "quantity": "30", "unit": "g"},
            {"name": "Parsley", "quantity": "15", "unit": "g"},
            {"name": "Olive oil", "quantity": "1", "unit": "tbsp"},
            {"name": "Lemon juice", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Drain and flake tuna.", "Combine with beans, capers, red onion, and parsley.", "Dress with olive oil and lemon juice."],
        "notes": "Serve on top of arugula for extra nutrients.",
    },
    {
        "title": "Lentil & Kale Soup",
        "about": "Hearty, fiber-rich lentil soup with kale, tomatoes, and warming spices. Vegan and freezer-friendly.",
        "category": "Vegan",
        "menuType": "Lunch",
        "calories": 310, "proteins": 18, "fat": 4, "carbs": 52,
        "servings": 4,
        "ingredients": [
            {"name": "Red lentils", "quantity": "200", "unit": "g"},
            {"name": "Kale (chopped)", "quantity": "100", "unit": "g"},
            {"name": "Diced tomatoes", "quantity": "400", "unit": "g"},
            {"name": "Vegetable broth", "quantity": "1000", "unit": "ml"},
            {"name": "Cumin", "quantity": "1", "unit": "tsp"},
            {"name": "Turmeric", "quantity": "0.5", "unit": "tsp"},
            {"name": "Garlic (minced)", "quantity": "3", "unit": "piece"},
        ],
        "directions": ["Sauté garlic and spices 1 min.", "Add lentils, tomatoes, and broth; bring to boil.", "Simmer 20 min until lentils are soft.", "Stir in kale and cook 5 min more."],
        "notes": "Freeze in portions for quick weekday lunches.",
    },
    {
        "title": "Grilled Salmon Power Bowl",
        "about": "Omega-3-rich grilled salmon over brown rice with edamame, avocado, and miso dressing.",
        "category": "Healthy",
        "menuType": "Lunch",
        "calories": 560, "proteins": 44, "fat": 22, "carbs": 42,
        "servings": 1,
        "ingredients": [
            {"name": "Salmon fillet", "quantity": "180", "unit": "g"},
            {"name": "Brown rice (cooked)", "quantity": "120", "unit": "g"},
            {"name": "Edamame", "quantity": "60", "unit": "g"},
            {"name": "Avocado", "quantity": "0.5", "unit": "piece"},
            {"name": "Shredded carrot", "quantity": "40", "unit": "g"},
            {"name": "Miso dressing", "quantity": "2", "unit": "tbsp"},
        ],
        "directions": ["Season salmon and grill 4 min per side.", "Assemble bowl with rice base.", "Add salmon, edamame, avocado, carrot.", "Drizzle with miso dressing."],
        "notes": "Substitute cauliflower rice for keto version.",
    },

    # ── DINNER ─────────────────────────────────────────────────
    {
        "title": "Baked Lemon Herb Salmon",
        "about": "Oven-baked salmon with lemon, dill, and garlic served with roasted asparagus. Clean, easy, and impressive.",
        "category": "Healthy",
        "menuType": "Dinner",
        "calories": 420, "proteins": 44, "fat": 20, "carbs": 12,
        "servings": 2,
        "ingredients": [
            {"name": "Salmon fillets", "quantity": "360", "unit": "g"},
            {"name": "Asparagus", "quantity": "200", "unit": "g"},
            {"name": "Lemon", "quantity": "1", "unit": "piece"},
            {"name": "Fresh dill", "quantity": "10", "unit": "g"},
            {"name": "Garlic (minced)", "quantity": "2", "unit": "piece"},
            {"name": "Olive oil", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Preheat oven to 200°C.", "Place salmon and asparagus on a baking sheet.", "Drizzle with olive oil, lemon juice, garlic, and dill.", "Bake 15–18 min until salmon flakes easily."],
        "notes": "Pairs well with quinoa or cauliflower rice.",
    },
    {
        "title": "Chicken Tikka Masala (Light)",
        "about": "Indian-inspired tikka masala with tender chicken in a creamy tomato sauce. Lightened with Greek yogurt.",
        "category": "Balanced",
        "menuType": "Dinner",
        "calories": 480, "proteins": 40, "fat": 18, "carbs": 35,
        "servings": 2,
        "ingredients": [
            {"name": "Chicken breast (cubed)", "quantity": "400", "unit": "g"},
            {"name": "Greek yogurt", "quantity": "100", "unit": "g"},
            {"name": "Crushed tomatoes", "quantity": "400", "unit": "g"},
            {"name": "Coconut milk (light)", "quantity": "100", "unit": "ml"},
            {"name": "Tikka masala paste", "quantity": "2", "unit": "tbsp"},
            {"name": "Garlic & ginger", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Marinate chicken in yogurt and spices 30 min.", "Brown chicken in a pan.", "Add paste, tomatoes, and coconut milk; simmer 20 min.", "Serve with brown rice or naan."],
        "notes": "Use half the coconut milk for fewer calories.",
    },
    {
        "title": "Turkey Meatball Zucchini Noodles",
        "about": "Low-carb zucchini noodles with lean turkey meatballs in a rich marinara. Comfort food without the guilt.",
        "category": "Clean Eating",
        "menuType": "Dinner",
        "calories": 380, "proteins": 38, "fat": 16, "carbs": 18,
        "servings": 2,
        "ingredients": [
            {"name": "Ground turkey", "quantity": "300", "unit": "g"},
            {"name": "Zucchini", "quantity": "3", "unit": "piece"},
            {"name": "Marinara sauce", "quantity": "200", "unit": "g"},
            {"name": "Parmesan cheese", "quantity": "20", "unit": "g"},
            {"name": "Garlic (minced)", "quantity": "2", "unit": "piece"},
            {"name": "Italian seasoning", "quantity": "1", "unit": "tsp"},
            {"name": "Egg", "quantity": "1", "unit": "piece"},
        ],
        "directions": ["Mix turkey, garlic, seasoning, and egg; form meatballs.", "Bake at 190°C for 20 min.", "Spiralize zucchini into noodles.", "Heat marinara, toss with zucchini noodles and meatballs."],
        "notes": "Don't overcook zucchini — it gets watery.",
    },
    {
        "title": "Teriyaki Tofu Bowl",
        "about": "Crispy baked tofu with homemade teriyaki sauce, broccoli, and sesame seeds over brown rice.",
        "category": "Vegan",
        "menuType": "Dinner",
        "calories": 440, "proteins": 22, "fat": 14, "carbs": 56,
        "servings": 2,
        "ingredients": [
            {"name": "Extra-firm tofu", "quantity": "400", "unit": "g"},
            {"name": "Brown rice (cooked)", "quantity": "200", "unit": "g"},
            {"name": "Broccoli florets", "quantity": "200", "unit": "g"},
            {"name": "Soy sauce", "quantity": "3", "unit": "tbsp"},
            {"name": "Honey or maple syrup", "quantity": "2", "unit": "tbsp"},
            {"name": "Sesame oil", "quantity": "1", "unit": "tsp"},
            {"name": "Sesame seeds", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Press and cube tofu; bake at 200°C for 25 min.", "Steam broccoli until tender.", "Make teriyaki sauce: soy sauce, sweetener, sesame oil.", "Toss tofu in sauce and serve over rice with broccoli."],
        "notes": "Freeze tofu before pressing for crispier result.",
    },
    {
        "title": "Stuffed Bell Peppers",
        "about": "Colorful bell peppers stuffed with seasoned lean ground beef, quinoa, and melted cheese.",
        "category": "Balanced",
        "menuType": "Dinner",
        "calories": 380, "proteins": 28, "fat": 14, "carbs": 34,
        "servings": 4,
        "ingredients": [
            {"name": "Bell peppers (large)", "quantity": "4", "unit": "piece"},
            {"name": "Lean ground beef", "quantity": "300", "unit": "g"},
            {"name": "Quinoa (cooked)", "quantity": "150", "unit": "g"},
            {"name": "Diced tomatoes", "quantity": "200", "unit": "g"},
            {"name": "Mozzarella cheese", "quantity": "60", "unit": "g"},
            {"name": "Italian seasoning", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Halve and deseed peppers; pre-bake 10 min at 190°C.", "Brown beef with seasoning; mix in quinoa and tomatoes.", "Fill peppers, top with cheese.", "Bake 20 min more until cheese bubbles."],
        "notes": "Substitute beef with lentils for a vegan version.",
    },
    {
        "title": "Vegetable Thai Green Curry",
        "about": "Fragrant Thai green curry loaded with mixed vegetables and tofu in creamy coconut milk.",
        "category": "Vegan",
        "menuType": "Dinner",
        "calories": 390, "proteins": 16, "fat": 20, "carbs": 42,
        "servings": 2,
        "ingredients": [
            {"name": "Green curry paste", "quantity": "2", "unit": "tbsp"},
            {"name": "Coconut milk", "quantity": "400", "unit": "ml"},
            {"name": "Extra-firm tofu", "quantity": "200", "unit": "g"},
            {"name": "Mixed vegetables", "quantity": "300", "unit": "g"},
            {"name": "Thai basil", "quantity": "15", "unit": "g"},
            {"name": "Fish sauce or soy sauce", "quantity": "1", "unit": "tbsp"},
            {"name": "Lime juice", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Fry curry paste in oil 1 min.", "Add coconut milk and bring to simmer.", "Add tofu and vegetables; cook 12 min.", "Finish with basil, fish sauce, and lime juice."],
        "notes": "Serve with jasmine rice or rice noodles.",
    },
    {
        "title": "Grilled Shrimp Tacos",
        "about": "Spicy grilled shrimp in corn tortillas with mango slaw, avocado crema, and pickled onions.",
        "category": "Healthy",
        "menuType": "Dinner",
        "calories": 420, "proteins": 32, "fat": 16, "carbs": 40,
        "servings": 2,
        "ingredients": [
            {"name": "Large shrimp", "quantity": "300", "unit": "g"},
            {"name": "Corn tortillas (small)", "quantity": "6", "unit": "piece"},
            {"name": "Mango (diced)", "quantity": "100", "unit": "g"},
            {"name": "Cabbage (shredded)", "quantity": "100", "unit": "g"},
            {"name": "Greek yogurt", "quantity": "60", "unit": "g"},
            {"name": "Avocado", "quantity": "0.5", "unit": "piece"},
            {"name": "Lime juice", "quantity": "2", "unit": "tbsp"},
            {"name": "Chili powder", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Season shrimp with chili and lime; grill 2 min per side.", "Mix mango, cabbage, and lime for slaw.", "Blend avocado and yogurt for crema.", "Assemble tacos with shrimp, slaw, and crema."],
        "notes": "Warm tortillas on the grill for 30 seconds.",
    },
    {
        "title": "Moroccan Lemon Chicken",
        "about": "Oven-roasted chicken thighs with preserved lemon, olives, and warming Moroccan spices.",
        "category": "Mediterranean",
        "menuType": "Dinner",
        "calories": 450, "proteins": 40, "fat": 26, "carbs": 12,
        "servings": 2,
        "ingredients": [
            {"name": "Chicken thighs (bone-in)", "quantity": "4", "unit": "piece"},
            {"name": "Preserved lemon", "quantity": "1", "unit": "piece"},
            {"name": "Kalamata olives", "quantity": "60", "unit": "g"},
            {"name": "Ras el hanout", "quantity": "2", "unit": "tsp"},
            {"name": "Garlic (minced)", "quantity": "3", "unit": "piece"},
            {"name": "Chicken broth", "quantity": "100", "unit": "ml"},
        ],
        "directions": ["Marinate chicken with spices and garlic overnight.", "Brown chicken skin-down 5 min.", "Add broth, lemon, and olives; roast 35 min at 190°C.", "Rest 5 min before serving."],
        "notes": "Serve with couscous or roasted cauliflower.",
    },
    {
        "title": "Black Bean & Sweet Potato Chili",
        "about": "Thick, hearty vegan chili with sweet potato, black beans, tomatoes, and smoky spices.",
        "category": "Vegan",
        "menuType": "Dinner",
        "calories": 350, "proteins": 16, "fat": 4, "carbs": 62,
        "servings": 4,
        "ingredients": [
            {"name": "Sweet potato (cubed)", "quantity": "300", "unit": "g"},
            {"name": "Black beans (cooked)", "quantity": "400", "unit": "g"},
            {"name": "Diced tomatoes", "quantity": "400", "unit": "g"},
            {"name": "Vegetable broth", "quantity": "400", "unit": "ml"},
            {"name": "Chipotle in adobo", "quantity": "1", "unit": "piece"},
            {"name": "Cumin", "quantity": "1.5", "unit": "tsp"},
            {"name": "Smoked paprika", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Sauté onion, garlic, and spices.", "Add sweet potato, beans, tomatoes, broth, and chipotle.", "Simmer 25 min until sweet potato is tender.", "Adjust seasoning and serve with toppings."],
        "notes": "Keeps well frozen for up to 3 months.",
    },
    {
        "title": "Garlic Butter Cod with Roasted Veggies",
        "about": "Flaky baked cod with garlic butter glaze alongside roasted Brussels sprouts and cherry tomatoes.",
        "category": "Clean Eating",
        "menuType": "Dinner",
        "calories": 320, "proteins": 38, "fat": 12, "carbs": 16,
        "servings": 2,
        "ingredients": [
            {"name": "Cod fillets", "quantity": "360", "unit": "g"},
            {"name": "Brussels sprouts", "quantity": "200", "unit": "g"},
            {"name": "Cherry tomatoes", "quantity": "150", "unit": "g"},
            {"name": "Butter", "quantity": "1", "unit": "tbsp"},
            {"name": "Garlic (minced)", "quantity": "3", "unit": "piece"},
            {"name": "Lemon zest", "quantity": "1", "unit": "tsp"},
            {"name": "Parsley", "quantity": "10", "unit": "g"},
        ],
        "directions": ["Halve Brussels sprouts; roast with tomatoes at 200°C for 20 min.", "Mix butter, garlic, and lemon zest.", "Top cod with butter mixture and bake 15 min.", "Garnish with parsley and serve."],
        "notes": "Don't overcook the fish — 12 min is usually enough.",
    },
    {
        "title": "Chicken & Vegetable Stir-Fry",
        "about": "Quick weeknight stir-fry with chicken breast and colorful veggies in a savory ginger soy sauce.",
        "category": "Healthy",
        "menuType": "Dinner",
        "calories": 380, "proteins": 36, "fat": 10, "carbs": 34,
        "servings": 2,
        "ingredients": [
            {"name": "Chicken breast (sliced)", "quantity": "300", "unit": "g"},
            {"name": "Broccoli florets", "quantity": "150", "unit": "g"},
            {"name": "Snap peas", "quantity": "100", "unit": "g"},
            {"name": "Bell peppers (sliced)", "quantity": "150", "unit": "g"},
            {"name": "Soy sauce", "quantity": "2", "unit": "tbsp"},
            {"name": "Fresh ginger", "quantity": "1", "unit": "tsp"},
            {"name": "Sesame oil", "quantity": "1", "unit": "tsp"},
            {"name": "Cornstarch", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Mix soy sauce, ginger, sesame oil, cornstarch for sauce.", "Stir-fry chicken on high heat 5 min.", "Add vegetables and toss 3 min.", "Add sauce, toss until glazed."],
        "notes": "High heat is key — don't crowd the pan.",
    },

    # ── SNACKS ─────────────────────────────────────────────────
    {
        "title": "Almond Butter Energy Balls",
        "about": "No-bake almond butter, oat, and honey bites. Perfect pre-workout snack.",
        "category": "Healthy",
        "menuType": "Snack",
        "calories": 180, "proteins": 6, "fat": 10, "carbs": 20,
        "servings": 12,
        "ingredients": [
            {"name": "Rolled oats", "quantity": "120", "unit": "g"},
            {"name": "Almond butter", "quantity": "90", "unit": "g"},
            {"name": "Honey", "quantity": "3", "unit": "tbsp"},
            {"name": "Dark chocolate chips", "quantity": "40", "unit": "g"},
            {"name": "Flaxseed (ground)", "quantity": "1", "unit": "tbsp"},
            {"name": "Vanilla extract", "quantity": "0.5", "unit": "tsp"},
        ],
        "directions": ["Mix all ingredients in a bowl.", "Refrigerate 30 min to firm up.", "Roll into 12 balls.", "Store in fridge up to 1 week."],
        "notes": "Add protein powder to boost macros.",
    },
    {
        "title": "Hummus & Veggie Platter",
        "about": "Creamy homemade hummus with an assortment of fresh cut vegetables for dipping.",
        "category": "Vegan",
        "menuType": "Snack",
        "calories": 230, "proteins": 8, "fat": 12, "carbs": 24,
        "servings": 2,
        "ingredients": [
            {"name": "Chickpeas (cooked)", "quantity": "240", "unit": "g"},
            {"name": "Tahini", "quantity": "2", "unit": "tbsp"},
            {"name": "Lemon juice", "quantity": "2", "unit": "tbsp"},
            {"name": "Garlic", "quantity": "1", "unit": "piece"},
            {"name": "Olive oil", "quantity": "1", "unit": "tbsp"},
            {"name": "Carrot sticks", "quantity": "100", "unit": "g"},
            {"name": "Cucumber slices", "quantity": "100", "unit": "g"},
        ],
        "directions": ["Blend chickpeas, tahini, lemon, garlic, and olive oil until smooth.", "Season with salt and cumin.", "Serve with cut vegetables."],
        "notes": "Thin with ice water for a creamier texture.",
    },
    {
        "title": "Cottage Cheese & Pineapple Bowl",
        "about": "High-protein cottage cheese topped with fresh pineapple chunks and a drizzle of honey.",
        "category": "High Protein",
        "menuType": "Snack",
        "calories": 200, "proteins": 20, "fat": 4, "carbs": 24,
        "servings": 1,
        "ingredients": [
            {"name": "Cottage cheese (1%)", "quantity": "200", "unit": "g"},
            {"name": "Pineapple chunks", "quantity": "80", "unit": "g"},
            {"name": "Honey", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Spoon cottage cheese into a bowl.", "Top with pineapple.", "Drizzle with honey."],
        "notes": "Mango or peach works great too.",
    },
    {
        "title": "Apple Slices with Peanut Butter",
        "about": "Simple, satisfying combination of crisp apple slices with natural peanut butter for healthy fats and fiber.",
        "category": "Balanced",
        "menuType": "Snack",
        "calories": 250, "proteins": 8, "fat": 14, "carbs": 28,
        "servings": 1,
        "ingredients": [
            {"name": "Apple", "quantity": "1", "unit": "piece"},
            {"name": "Natural peanut butter", "quantity": "2", "unit": "tbsp"},
        ],
        "directions": ["Slice apple into wedges.", "Serve with peanut butter for dipping."],
        "notes": "Sprinkle cinnamon on apple for extra flavor.",
    },
    {
        "title": "Mixed Nuts & Dark Chocolate",
        "about": "A mindful snack of raw almonds, walnuts, and dark chocolate chips. Satisfying and nutrient-dense.",
        "category": "Keto",
        "menuType": "Snack",
        "calories": 280, "proteins": 8, "fat": 24, "carbs": 14,
        "servings": 1,
        "ingredients": [
            {"name": "Almonds", "quantity": "20", "unit": "g"},
            {"name": "Walnuts", "quantity": "20", "unit": "g"},
            {"name": "Cashews", "quantity": "15", "unit": "g"},
            {"name": "Dark chocolate chips (85%)", "quantity": "15", "unit": "g"},
        ],
        "directions": ["Portion out nuts and chocolate into a small bowl.", "Enjoy mindfully."],
        "notes": "Pre-portion into containers for easy grab-and-go.",
    },
    {
        "title": "Protein Smoothie",
        "about": "Creamy blended protein shake with banana, almond milk, whey protein, and natural peanut butter.",
        "category": "High Protein",
        "menuType": "Snack",
        "calories": 330, "proteins": 32, "fat": 10, "carbs": 32,
        "servings": 1,
        "ingredients": [
            {"name": "Whey protein (vanilla)", "quantity": "30", "unit": "g"},
            {"name": "Banana (frozen)", "quantity": "1", "unit": "piece"},
            {"name": "Almond milk", "quantity": "300", "unit": "ml"},
            {"name": "Peanut butter", "quantity": "1", "unit": "tbsp"},
            {"name": "Ice cubes", "quantity": "4", "unit": "piece"},
        ],
        "directions": ["Add all ingredients to a blender.", "Blend until smooth.", "Drink immediately."],
        "notes": "Add spinach — you won't taste it.",
    },
    {
        "title": "Rice Cake with Avocado & Tuna",
        "about": "Light and satisfying rice cake stacked with mashed avocado and flaked tuna. Only 200 calories.",
        "category": "Clean Eating",
        "menuType": "Snack",
        "calories": 200, "proteins": 16, "fat": 8, "carbs": 16,
        "servings": 1,
        "ingredients": [
            {"name": "Rice cakes", "quantity": "2", "unit": "piece"},
            {"name": "Canned tuna (in water)", "quantity": "80", "unit": "g"},
            {"name": "Avocado", "quantity": "0.25", "unit": "piece"},
            {"name": "Lemon juice", "quantity": "1", "unit": "tsp"},
        ],
        "directions": ["Mash avocado with lemon juice.", "Drain and flake tuna.", "Spread avocado on rice cakes, top with tuna."],
        "notes": "Season with black pepper and everything bagel spice.",
    },

    # ── ALL-DAY / FLEXIBLE ──────────────────────────────────────
    {
        "title": "Quinoa Power Salad",
        "about": "Nutrient-dense quinoa salad with roasted chickpeas, kale, dried cranberries, and lemon tahini dressing.",
        "category": "Vegan",
        "menuType": "All-Day",
        "calories": 440, "proteins": 18, "fat": 16, "carbs": 58,
        "servings": 2,
        "ingredients": [
            {"name": "Quinoa (cooked)", "quantity": "160", "unit": "g"},
            {"name": "Kale (massaged)", "quantity": "100", "unit": "g"},
            {"name": "Chickpeas (roasted)", "quantity": "120", "unit": "g"},
            {"name": "Dried cranberries", "quantity": "30", "unit": "g"},
            {"name": "Pumpkin seeds", "quantity": "20", "unit": "g"},
            {"name": "Tahini", "quantity": "2", "unit": "tbsp"},
            {"name": "Lemon juice", "quantity": "2", "unit": "tbsp"},
        ],
        "directions": ["Roast chickpeas 25 min at 200°C until crispy.", "Massage kale with olive oil until softened.", "Combine all ingredients.", "Whisk tahini, lemon juice, and water for dressing."],
        "notes": "Keeps for 3 days — perfect for meal prep.",
    },
    {
        "title": "Egg & Veggie Muffins",
        "about": "Portable egg muffin cups with spinach, bell pepper, and feta. Great for meal prep.",
        "category": "High Protein",
        "menuType": "All-Day",
        "calories": 180, "proteins": 16, "fat": 10, "carbs": 6,
        "servings": 6,
        "ingredients": [
            {"name": "Eggs", "quantity": "8", "unit": "piece"},
            {"name": "Baby spinach", "quantity": "60", "unit": "g"},
            {"name": "Bell pepper (diced)", "quantity": "80", "unit": "g"},
            {"name": "Feta cheese", "quantity": "50", "unit": "g"},
            {"name": "Milk", "quantity": "60", "unit": "ml"},
            {"name": "Italian seasoning", "quantity": "0.5", "unit": "tsp"},
        ],
        "directions": ["Preheat oven to 180°C, grease a muffin tin.", "Whisk eggs with milk and seasoning.", "Divide veggies into cups, pour in egg mixture.", "Bake 20 min until set."],
        "notes": "Reheat in microwave 45 seconds.",
    },
    {
        "title": "Green Detox Smoothie Bowl",
        "about": "Thick blended spinach, banana, and pineapple smoothie bowl with kiwi, seeds, and coconut.",
        "category": "Vegan",
        "menuType": "All-Day",
        "calories": 300, "proteins": 8, "fat": 8, "carbs": 52,
        "servings": 1,
        "ingredients": [
            {"name": "Baby spinach", "quantity": "60", "unit": "g"},
            {"name": "Banana (frozen)", "quantity": "1", "unit": "piece"},
            {"name": "Pineapple chunks", "quantity": "100", "unit": "g"},
            {"name": "Coconut milk", "quantity": "80", "unit": "ml"},
            {"name": "Kiwi (sliced)", "quantity": "1", "unit": "piece"},
            {"name": "Chia seeds", "quantity": "1", "unit": "tbsp"},
            {"name": "Coconut flakes", "quantity": "10", "unit": "g"},
        ],
        "directions": ["Blend spinach, banana, pineapple, and coconut milk until thick.", "Pour into bowl.", "Top with kiwi, chia seeds, and coconut."],
        "notes": "Add ginger for a metabolism boost.",
    },
    {
        "title": "Caprese Salad with Grilled Chicken",
        "about": "Italian classic elevated with grilled chicken breast. Fresh mozzarella, heirloom tomatoes, and basil.",
        "category": "Mediterranean",
        "menuType": "All-Day",
        "calories": 420, "proteins": 40, "fat": 22, "carbs": 10,
        "servings": 2,
        "ingredients": [
            {"name": "Chicken breast", "quantity": "280", "unit": "g"},
            {"name": "Fresh mozzarella", "quantity": "120", "unit": "g"},
            {"name": "Heirloom tomatoes", "quantity": "200", "unit": "g"},
            {"name": "Fresh basil", "quantity": "20", "unit": "g"},
            {"name": "Extra virgin olive oil", "quantity": "1", "unit": "tbsp"},
            {"name": "Balsamic glaze", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Grill chicken 6 min per side; let rest 5 min.", "Slice chicken, tomatoes, and mozzarella.", "Arrange overlapping on a plate.", "Drizzle with olive oil and balsamic glaze, top with basil."],
        "notes": "Use burrata for an indulgent upgrade.",
    },
    {
        "title": "Keto Egg Salad Lettuce Cups",
        "about": "Classic creamy egg salad with avocado mayo served in crisp butter lettuce cups. Zero carb.",
        "category": "Keto",
        "menuType": "All-Day",
        "calories": 280, "proteins": 18, "fat": 22, "carbs": 4,
        "servings": 2,
        "ingredients": [
            {"name": "Hard-boiled eggs", "quantity": "4", "unit": "piece"},
            {"name": "Avocado mayo", "quantity": "2", "unit": "tbsp"},
            {"name": "Dijon mustard", "quantity": "1", "unit": "tsp"},
            {"name": "Celery (diced)", "quantity": "2", "unit": "piece"},
            {"name": "Butter lettuce leaves", "quantity": "6", "unit": "piece"},
            {"name": "Chives", "quantity": "10", "unit": "g"},
        ],
        "directions": ["Chop eggs and celery.", "Mix with mayo, mustard, and chives.", "Spoon into lettuce cups."],
        "notes": "Season well — eggs need generous salt.",
    },
    {
        "title": "Poke Bowl",
        "about": "Hawaiian-inspired poke bowl with sushi-grade tuna, edamame, avocado, and spicy mayo over rice.",
        "category": "Healthy",
        "menuType": "All-Day",
        "calories": 520, "proteins": 38, "fat": 18, "carbs": 52,
        "servings": 1,
        "ingredients": [
            {"name": "Sushi-grade tuna (diced)", "quantity": "180", "unit": "g"},
            {"name": "Sushi rice (cooked)", "quantity": "120", "unit": "g"},
            {"name": "Edamame", "quantity": "60", "unit": "g"},
            {"name": "Avocado", "quantity": "0.5", "unit": "piece"},
            {"name": "Cucumber (sliced)", "quantity": "60", "unit": "g"},
            {"name": "Soy sauce", "quantity": "1", "unit": "tbsp"},
            {"name": "Sesame oil", "quantity": "0.5", "unit": "tsp"},
            {"name": "Sriracha mayo", "quantity": "1", "unit": "tbsp"},
        ],
        "directions": ["Toss tuna with soy sauce and sesame oil.", "Arrange rice in a bowl.", "Top with tuna, edamame, avocado, cucumber.", "Drizzle with sriracha mayo."],
        "notes": "Only use sashimi-grade fish for raw preparations.",
    },
    {
        "title": "Loaded Sweet Potato",
        "about": "Baked sweet potato loaded with black beans, Greek yogurt, salsa, and shredded cheese. Satisfying comfort food.",
        "category": "Vegetarian",
        "menuType": "All-Day",
        "calories": 460, "proteins": 20, "fat": 8, "carbs": 78,
        "servings": 1,
        "ingredients": [
            {"name": "Large sweet potato", "quantity": "1", "unit": "piece"},
            {"name": "Black beans (cooked)", "quantity": "80", "unit": "g"},
            {"name": "Greek yogurt", "quantity": "60", "unit": "g"},
            {"name": "Salsa", "quantity": "60", "unit": "g"},
            {"name": "Cheddar cheese (shredded)", "quantity": "30", "unit": "g"},
            {"name": "Green onions", "quantity": "15", "unit": "g"},
        ],
        "directions": ["Pierce sweet potato and microwave 8–10 min or bake 45 min at 200°C.", "Cut open and fluff the inside.", "Load with beans, yogurt, salsa, and cheese.", "Garnish with green onions."],
        "notes": "The Greek yogurt mimics sour cream with more protein.",
    },
    {
        "title": "Greek Salad with Falafel",
        "about": "Classic Greek salad with crispy baked falafel, feta, and a lemon-oregano vinaigrette.",
        "category": "Mediterranean",
        "menuType": "All-Day",
        "calories": 410, "proteins": 16, "fat": 22, "carbs": 40,
        "servings": 2,
        "ingredients": [
            {"name": "Falafel (baked)", "quantity": "6", "unit": "piece"},
            {"name": "Romaine lettuce", "quantity": "120", "unit": "g"},
            {"name": "Cherry tomatoes", "quantity": "100", "unit": "g"},
            {"name": "Cucumber", "quantity": "100", "unit": "g"},
            {"name": "Kalamata olives", "quantity": "40", "unit": "g"},
            {"name": "Feta cheese", "quantity": "60", "unit": "g"},
            {"name": "Olive oil", "quantity": "1.5", "unit": "tbsp"},
            {"name": "Lemon juice", "quantity": "1.5", "unit": "tbsp"},
            {"name": "Dried oregano", "quantity": "0.5", "unit": "tsp"},
        ],
        "directions": ["Toss vegetables with olive oil, lemon, and oregano.", "Add olives and feta.", "Serve topped with warm falafel."],
        "notes": "Store-bought falafel works fine — just bake until crispy.",
    },
    {
        "title": "Shakshuka",
        "about": "North African eggs poached in a spiced tomato and pepper sauce. One pan, full of flavor.",
        "category": "Vegetarian",
        "menuType": "All-Day",
        "calories": 290, "proteins": 18, "fat": 16, "carbs": 22,
        "servings": 2,
        "ingredients": [
            {"name": "Eggs", "quantity": "4", "unit": "piece"},
            {"name": "Crushed tomatoes", "quantity": "400", "unit": "g"},
            {"name": "Bell peppers (sliced)", "quantity": "150", "unit": "g"},
            {"name": "Onion", "quantity": "1", "unit": "piece"},
            {"name": "Garlic (minced)", "quantity": "3", "unit": "piece"},
            {"name": "Cumin", "quantity": "1", "unit": "tsp"},
            {"name": "Smoked paprika", "quantity": "1", "unit": "tsp"},
            {"name": "Chili flakes", "quantity": "0.5", "unit": "tsp"},
            {"name": "Feta cheese", "quantity": "40", "unit": "g"},
        ],
        "directions": ["Sauté onion, garlic, and peppers 8 min.", "Add spices, then crushed tomatoes; simmer 10 min.", "Make wells and crack in eggs.", "Cover and cook 8 min. Top with feta."],
        "notes": "Serve with crusty bread to scoop up the sauce.",
    },
    {
        "title": "Mango Chicken Brown Rice Bowl",
        "about": "Tropical bowl with grilled chicken, fresh mango salsa, black beans, and cilantro-lime rice.",
        "category": "Balanced",
        "menuType": "All-Day",
        "calories": 490, "proteins": 38, "fat": 10, "carbs": 62,
        "servings": 2,
        "ingredients": [
            {"name": "Chicken breast", "quantity": "300", "unit": "g"},
            {"name": "Brown rice (cooked)", "quantity": "200", "unit": "g"},
            {"name": "Mango (diced)", "quantity": "120", "unit": "g"},
            {"name": "Black beans", "quantity": "80", "unit": "g"},
            {"name": "Red onion", "quantity": "30", "unit": "g"},
            {"name": "Cilantro", "quantity": "15", "unit": "g"},
            {"name": "Lime juice", "quantity": "2", "unit": "tbsp"},
            {"name": "Jalapeño", "quantity": "1", "unit": "piece"},
        ],
        "directions": ["Grill chicken with cumin and lime; slice thin.", "Mix rice with cilantro and lime juice.", "Make mango salsa with mango, onion, jalapeño, cilantro.", "Assemble bowls and top with salsa."],
        "notes": "Sub cauliflower rice to save 100 calories.",
    },
]


async def seed_admin_meals():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]

    print("Seeding admin_meals collection...")
    inserted = 0
    skipped = 0

    for meal in MEALS:
        existing = await db.admin_meals.find_one({"title": meal["title"]})
        if existing:
            skipped += 1
            continue

        doc = {
            **meal,
            "imageUrl": random.choice(FOOD_IMAGES),
            "videoUrl": "",
            "notes": meal.get("notes", ""),
            "status": "active",
            "user_generated": False,
            "deleted": False,
            "favorite_count": random.randint(0, 80),
            "created_at": now_utc(),
            "updated_at": now_utc(),
            "created_by": "system",
        }
        await db.admin_meals.insert_one(doc)
        inserted += 1
        print(f"  ✓ {meal['title']}")

    print(f"\nDone. Inserted: {inserted}, Skipped (already exist): {skipped}")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed_admin_meals())
